version: "3.3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: bs_assignment
    volumes:
      - ./mysqldb:/var/lib/mysql:rw
    restart: always
  web:
    build: ./
    environment:
      DATABASE_NAME: bs_assignment
      DATABASE_USER: root
      DATABASE_PASS: rootpw
      DATABASE_URL: db
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
